### ISSUE TITLE
PG::DuplicateTable: ERROR:  relation "accounts" already exists

### ISSUE THREAD

**Issue by romenigld** [radar/twist#17]
I am in the page 16 and when I generate the model account:
`rails g model account name:string`
and run 
`rake db:migrate`
I get an error of duplicating table, the table was already created before and with more columns.
```
-- create_table(:accounts)
rails aborted!
StandardError: An error has occurred, this and all later migrations canceled:

PG::DuplicateTable: ERROR:  relation "accounts" already exists
: CREATE TABLE "accounts" ("id" serial primary key, "name" character varying, "created_at" timestamp NOT NULL, "updated_at" timestamp NOT NULL)
```
And I saw this is with rails 5 and the command is not rake anymore, it's `rails db:migrate`.

What I need to do now for continuing? 
because when I try to run I'm getting this error: 

```
rspec spec/features/accounts/sign_up_spec.rb
/Users/romenigld/.rvm/gems/ruby-2.3.3/gems/activerecord-5.0.2/lib/active_record/migration.rb:573:in `check_pending!':  (ActiveRecord::PendingMigrationError)

Migrations are pending. To resolve this issue, run:

        bin/rails db:migrate RAILS_ENV=test

```

And I try to do what's is recommend and it was no solved.
`        bin/rails db:migrate RAILS_ENV=test
`

**Comment by romenigld** [comment]
I delete the model generated in the folder db. Then I run the:
`rspec spec/features/accounts/sign_up_spec.rb
`
and I have the same error like the ebook:
undefined method `accounts_path' for ...

```
Failures:

  1) Accounts creating an account
     Failure/Error: <%= simple_form_for(@account) do |account| %>

     ActionView::Template::Error:
       undefined method `accounts_path' for #<#<Class:0x007fd201bd02b0>:0x007fd201b91e20>
       Did you mean?  font_path
```
so I will try to continue.

**Comment by radar** [comment]
Hi again :) The table absolutely shouldn't exist. The only way I can think of it existing is if you had already created the migration. It's hard to know without seeing the codebase itself.

Regarding `rake db:migrate` and `rails db:migrate`, they're now interchangeable. `rails db:migrate` actually ends up calling `rake db:migrate`. 

Regarding the `accounts_path` method missing, it's likely that you didn't add the accounts route. Again, I don't know for certain as I can't see the code.

Could you please put your version of Twist up on GitHub so that I can see it?

Thanks!

**Comment by romenigld** [comment]
Hello Ryan Bigg, I stop yesterday in the page 18. 
So the only problem was for to create the model accounts that already exists. And so the terminal complains that error` PG::DuplicateTable: ERROR: `.  
So I delete that migration and was posible to continue the book. 
The rest I understand very well I just put the results for shows you I'm not anymore with doubt and I'm continuing reading the book successfully.
So I just do the first commit of the book. And I will continue to reading now.
So here is my repository if you want to watch how i'm going:
[romenigld/twist](https://github.com/romenigld/twist)
Thank's for reply, have a good day!

**Comment by romenigld** [comment]
Hello Ryan I'm in the page 21 and the tables and columns is already created. So I don't need to do the migrations like in that page:
`rails g migration add_owner_id_to_accounts owner_id:integer`

my rails console:
```
Account.column_names
=> ["id",
 "name",
 "created_at",
 "updated_at",
 "owner_id",
 "subdomain",
 "stripe_customer_id",
 "plan_id",
 "stripe_subscription_id",
 "stripe_subscription_status",
 "card_last_4",
 "card_brand",
 "card_expiry_month",
 "card_expiry_year"]
```
So what you recommend(wait for a new version or continue with this sample)?

**Comment by romenigld** [comment]
So I have a different error on the page 25 when I change the  `app/controllers/accounts_controller.rb`
for `redirect_to root_url(subdomain: account.subdomain)`

When I try `rspec spec/features/accounts/sign_up_spec.rb`
I have a different failure:
```
F

Failures:

  1) Accounts creating an account
     Failure/Error: expect(page).to have_content("Signed in as test@example.com")
       expected to find text "Signed in as test@example.com" in "Twist | Sign in Create a new account"
```

the failure expected on the book is in the flash_notice:

```
Failure/Error: within(".flash_notice") do
Capybara::ElementNotFound:
Unable to find css ".flash_notice"
```

**Comment by twist-fetcher** [comment]
Which branch did you start with? It looks like you've started with the stripe branch instead of the master branch.

**Comment by romenigld** [comment]
was the master I just have this:
```
git branch
* master
```

**Comment by radar** [comment]
I don't see the create accounts migration. I suspect it may have run twice, but I don't know why. Try to recreate it and then run rake db:reset to reset the state of your database.

**Comment by romenigld** [comment]
So I try this:

```
$ rails g model account name:string
      invoke  active_record
      create    db/migrate/20170406153248_create_accounts.rb
    conflict    app/models/account.rb
  Overwrite /Users/romenigld/workspace/ebooks/Multitenancy with Rails 2nd Edition/twist/app/models/account.rb? (enter "h" for help) [Ynaqdh] y
       force    app/models/account.rb
      invoke    rspec
      create      spec/models/account_spec.rb
➜  twist git:(master) ✗ rake db:reset
Dropped database 'twist_dev'
Dropped database 'twist_test'
Created database 'twist_dev'
Created database 'twist_test'
-- enable_extension("plpgsql")
   -> 0.0382s
-- create_table("accounts", {:force=>:cascade})
   -> 0.0170s
-- create_table("books", {:force=>:cascade})
   -> 0.0099s
-- create_table("chapters", {:force=>:cascade})
   -> 0.0188s
-- create_table("comments", {:force=>:cascade})
   -> 0.0203s
-- create_table("elements", {:force=>:cascade})
   -> 0.0118s
-- create_table("images", {:force=>:cascade})
   -> 0.0104s
-- create_table("invitations", {:force=>:cascade})
   -> 0.0150s
-- create_table("memberships", {:force=>:cascade})
   -> 0.0114s
-- create_table("notes", {:force=>:cascade})
   -> 0.0110s
-- create_table("plans", {:force=>:cascade})
   -> 0.0051s
-- create_table("subscription_events", {:force=>:cascade})
   -> 0.0128s
-- create_table("users", {:force=>:cascade})
   -> 0.0215s
-- add_foreign_key("accounts", "plans")
   -> 0.0028s
-- add_foreign_key("books", "accounts")
   -> 0.0019s
-- add_foreign_key("invitations", "accounts")
   -> 0.0018s
-- add_foreign_key("memberships", "accounts")
   -> 0.0018s
-- add_foreign_key("memberships", "users")
   -> 0.0021s
-- add_foreign_key("subscription_events", "accounts")
   -> 0.0017s
-- initialize_schema_migrations_table()
   -> 0.0045s
-- enable_extension("plpgsql")
   -> 0.0359s
-- create_table("accounts", {:force=>:cascade})
   -> 0.0270s
-- create_table("books", {:force=>:cascade})
   -> 0.0192s
-- create_table("chapters", {:force=>:cascade})
   -> 0.0231s
-- create_table("comments", {:force=>:cascade})
   -> 0.0118s
-- create_table("elements", {:force=>:cascade})
   -> 0.0157s
-- create_table("images", {:force=>:cascade})
   -> 0.0111s
-- create_table("invitations", {:force=>:cascade})
   -> 0.0259s
-- create_table("memberships", {:force=>:cascade})
   -> 0.0138s
-- create_table("notes", {:force=>:cascade})
   -> 0.0186s
-- create_table("plans", {:force=>:cascade})
   -> 0.0056s
-- create_table("subscription_events", {:force=>:cascade})
   -> 0.0122s
-- create_table("users", {:force=>:cascade})
   -> 0.0208s
-- add_foreign_key("accounts", "plans")
   -> 0.0072s
-- add_foreign_key("books", "accounts")
   -> 0.0035s
-- add_foreign_key("invitations", "accounts")
   -> 0.0019s
-- add_foreign_key("memberships", "accounts")
   -> 0.0017s
-- add_foreign_key("memberships", "users")
   -> 0.0016s
-- add_foreign_key("subscription_events", "accounts")
   -> 0.0019s
-- initialize_schema_migrations_table()
   -> 0.0041s
You have 1 pending migration:
  20170406153248 CreateAccounts
Run `rails db:migrate` to update your database then try again.
➜  twist git:(master) ✗ rails db:migrate
== 20170406153248 CreateAccounts: migrating ===================================
-- create_table(:accounts)
rails aborted!
StandardError: An error has occurred, this and all later migrations canceled:

PG::DuplicateTable: ERROR:  relation "accounts" already exists
: CREATE TABLE "accounts" ("id" serial primary key, "name" character varying, "created_at" timestamp NOT NULL, "updated_at" timestamp NOT NULL)
```

**Comment by twist-fetcher** [comment]
At this point you definitely shouldn't have the accounts, invitations or subscription events tables already. Can you please show me the git log of the last few commits, up to and including the most recent one of mine that you have there?

**Comment by romenigld** [comment]
Which kind of git log you want? this `git log --oneline` serves?

```
$ git log --oneline

9d9f781 Accounts are now linked to owners
3363995 Added accounts
d1065a1 Escape paths in Git using Shellwords
178fc6a Use rm_rf to delete markdown_book_test directory in tests
a44ab25 Bump Rails to 5.0.2
883d079 Sign out via delete
bfb1396 Merge branch 'rails-5-upgrade'
aae0e87 Bump Ruby + Bundler versions
a68ece6 Add silence_stream to Git.rb
fe253b8 Bump Rails dependencies
62d24c6 Bump rake version
2c0e86e Enable Pygments highlighting in all envs
8c88d31 Uncomment git.update
b14f9ec Space out ols and uls
f9ad22b Merge pull request #12 from zhaqiang/remove-unnecessary-private-keyword
bcf8867 Remove unnecessary private keyword
f107303 Bump Ruby version
ca6b1a5 Deal with deprecation warnings
5726e03 Use right method for sign out link
a4d3d67 Update capybara
db89b23 Update stylesheets
8af149a Remove deprecated silence methods from git.rb
b6adf09 Rails 5 update config
acd639d before_filter -> before_action
d8feff0 replace serve_static_file and static_cache_control in test.rb
62cf185 Define versions in migrations
3ff6362 update binstubs
4b14c5d Update schema
f126b4c Update dependencies
3cdfbb9 Make tests faster by not calling Pygments in them
a898270 Remove 'account' column from books + invitations table from schema
e32a12f Do not require_tree in application.js
b51f135 Add logo
9ad6812 Style asides and tips the same way
43295a0 Add support for ch2 in markdown book test to book_spec
fc51565 Ensure chapter navigation works
e636c7e Move previous / next chapter logic into Chapter model
28760a7 Fix previous / next chapter links
f0e353b Reduce letter spacing so that code examples are less-likely to overflow
eced203 Fix markdown chapter process specs
5ca08e3 Correct chapter spec tests
:
```

**Comment by radar** [comment]
Sorry about that. Could you please pull from my repository again? I realised that my `db/schema.rb` contained the tables from MTWR, which is another failure on my behalf. This only becomes a problem when someone runs `rake db:reset`, which is what you're doing.

e64d144 is the commit which should fix this up.

**Comment by romenigld** [comment]
Don't worry Ryan, I will do that. 
And other thing's I saw some bit problem's like a link not working. 
Should I inform you here to help you??
Have a great weekend, Thank's!

**Comment by twist-fetcher** [comment]
Yes please tell me about the link that doesn't work

**Comment by romenigld** [comment]
Page 9 in the part "If you get stuck...":
link `https://github.com/radar/twist/tree/mtwr-walkthrough`

**Comment by romenigld** [comment]
And another thing I will delete the twist app. I need to drop the table or do something with database before delete??

**Comment by romenigld** [comment]
And another question what you recommend for me to push the twist app for my repository?
the other time I do with the 
` git remote set-url origin http://github.com/my_user/my_repos`
But I notice the original app has sometimes updates and I want to have them. 
Then it's better I do this with what type of ways?:
`git remote add personal http://github.com/my_user/my_repos`
or with upstream:
```
$ git remote rename origin upstream
$ git remote add origin http://github.com/my_user/my_repos
```
I watched this information [here](http://stackoverflow.com/questions/18200248/cloning-a-repo-from-someone-elses-github-and-pushing-it-to-a-repo-on-my-github). If you knows what is better for do this I will appreciate!

**Comment by romenigld** [comment]
other error is the page 16 the correct error for show is this:

```
 Failure/Error: @account = Account.new

     NameError:
       uninitialized constant AccountsController::Account
```

and not:
`  Failure/Error: click_link "Create a new account"`

**Comment by romenigld** [comment]
In that page 16 I'm having the same problems that the account already exists, maybe it's the other time. 

```
rake db:migrate
== 20170407182118 CreateAccounts: migrating ===================================
-- create_table(:accounts)
rake aborted!
StandardError: An error has occurred, this and all later migrations canceled:

PG::DuplicateTable: ERROR:  relation "accounts" already exists
: CREATE TABLE "accounts" ("id" serial primary key, "name" character varying, "created_at" timestamp NOT NULL, "updated_at" timestamp NOT NULL)
```
So I try the `rake db:reset ` and work's successfully!

```
rake db:reset
Dropped database 'twist_dev'
Dropped database 'twist_test'
Created database 'twist_dev'
Created database 'twist_test'
-- enable_extension("plpgsql")
   -> 0.0358s
-- create_table("books", {:force=>:cascade})
   -> 0.0091s
-- create_table("chapters", {:force=>:cascade})
   -> 0.0147s
-- create_table("comments", {:force=>:cascade})
   -> 0.0084s
-- create_table("elements", {:force=>:cascade})
   -> 0.0087s
-- create_table("images", {:force=>:cascade})
   -> 0.0088s
-- create_table("notes", {:force=>:cascade})
   -> 0.0167s
-- create_table("users", {:force=>:cascade})
   -> 0.0141s
-- initialize_schema_migrations_table()
   -> 0.0041s
-- enable_extension("plpgsql")
   -> 0.0383s
-- create_table("books", {:force=>:cascade})
   -> 0.0072s
-- create_table("chapters", {:force=>:cascade})
   -> 0.0164s
-- create_table("comments", {:force=>:cascade})
   -> 0.0080s
-- create_table("elements", {:force=>:cascade})
   -> 0.0109s
-- create_table("images", {:force=>:cascade})
   -> 0.0084s
-- create_table("notes", {:force=>:cascade})
   -> 0.0079s
-- create_table("users", {:force=>:cascade})
   -> 0.0139s
-- initialize_schema_migrations_table()
   -> 0.0036s
You have 1 pending migration:
  20170407182118 CreateAccounts
Run `rails db:migrate` to update your database then try again.
➜  twist git:(master) ✗ rake db:migrate
== 20170407182118 CreateAccounts: migrating ===================================
-- create_table(:accounts)
   -> 0.0161s
== 20170407182118 CreateAccounts: migrated (0.0161s) ==========================
```

**Comment by romenigld** [comment]
So when I try to run the rspec command I have this error:
```
rspec spec/features/accounts/sign_up_spec.rb
rails aborted!
ActiveRecord::EnvironmentMismatchError: You are attempting to modify a database that was last run in `development` environment.
You are running in `test` environment. If you are sure you want to continue, first set the environment using:

        bin/rails db:environment:set RAILS_ENV=test

/Users/romenigld/.rvm/gems/ruby-2.3.3/gems/activerecord-5.0.2/lib/active_record/tasks/database_tasks.rb:55:in `check_protected_environments!'
/Users/romenigld/.rvm/gems/ruby-2.3.3/gems/activerecord-5.0.2/lib/active_record/railties/databases.rake:11:in `block (2 levels) in <top (required)>'
/Users/romenigld/.rvm/gems/ruby-2.3.3/gems/activerecord-5.0.2/lib/active_record/railties/databases.rake:375:in `block (3 levels) in <top (required)>'
/Users/romenigld/.rvm/gems/ruby-2.3.3/gems/railties-5.0.2/lib/rails/commands/rake_proxy.rb:14:in `block in run_rake_task'
/Users/romenigld/.rvm/gems/ruby-2.3.3/gems/railties-5.0.2/lib/rails/commands/rake_proxy.rb:11:in `run_rake_task'
/Users/romenigld/.rvm/gems/ruby-2.3.3/gems/railties-5.0.2/lib/rails/commands/commands_tasks.rb:51:in `run_command!'
/Users/romenigld/.rvm/gems/ruby-2.3.3/gems/railties-5.0.2/lib/rails/commands.rb:18:in `<top (required)>'
bin/rails:4:in `require'
bin/rails:4:in `<main>'
Tasks: TOP => db:test:load => db:test:purge => db:check_protected_environments
(See full trace by running task with --trace)
/Users/romenigld/.rvm/gems/ruby-2.3.3/gems/activerecord-5.0.2/lib/active_record/migration.rb:573:in `check_pending!':  (ActiveRecord::PendingMigrationError)

Migrations are pending. To resolve this issue, run:

        bin/rails db:migrate RAILS_ENV=test

```

So I run this what complained me and works:

```
bin/rails db:environment:set RAILS_ENV=test
➜  twist git:(master) ✗ rspec spec/features/accounts/sign_up_spec.rb
F

Failures:

  1)  Accounts creating an account
     Failure/Error: <%= simple_form_for(@account) do |account| %>

     ActionView::Template::Error:
       undefined method `accounts_path' for #<#<Class:0x007fe287906e58>:0x007fe2878f4758>
       Did you mean?  font_path
```

**Comment by radar** [comment]
> And another thing I will delete the twist app for pull again the code.
I need to drop the table or do something with database before delete??

Running `rake db:reset` will do this for you.


----

The "undefined method" error is expected. The book says to fix this you need to define a route:

```ruby
post "/accounts", to: "accounts#create", as: :accounts
```

**Comment by radar** [comment]
Regarding repo config:

```
git remote add personal git@github.com:romenigld/twist
```

This is what I would recommend you do, then `git push personal master`

**Comment by romenigld** [comment]
No, you don't understand me sorry, look on the page 16 has this:

```
 Failure/Error: click_link "Create a new account"
   NameError:
     uninitialized constant AccountsController::Account

```
the correct error for the ebook on page 16 is this error:
```
Failure/Error: @account = Account.new
 NameError:
     uninitialized constant AccountsController::Account

```

**Comment by twist-fetcher** [comment]
You're right here that the error message is different. I saw it myself tonight during my read through. I have fixed it up in my local copy now, and you'll see the fix when I publish a new edition in a few weeks time.

**Comment by radar** [comment]
I should really reconfigure my email so that I use the right user...
