### ISSUE TITLE
No such file or directory Book.txt

### ISSUE THREAD

**Issue by victor-soto** [radar/twist#25]
Hi, I have an error in comments_spec.rb, I ran this test only and retrieve this error:

`Failures:

  1) commenting as an account's owner rejecting a note
     Failure/Error: lines = File.readlines("Book.txt")
     
     Errno::ENOENT:
       No such file or directory @ rb_sysopen - Book.txt
     # ./app/workers/book_worker.rb:15:in `readlines'
     # ./app/workers/book_worker.rb:15:in `block in perform'
     # ./app/workers/book_worker.rb:14:in `chdir'
     # ./app/workers/book_worker.rb:14:in `perform'
     # ./spec/support/book_helpers.rb:12:in `create_book!'
     # ./spec/features/comments_spec.rb:6:in `block (2 levels) in <top (required)>'
     # ./spec/rails_helper.rb:40:in `block (3 levels) in <top (required)>'
     # /home/victor/.rvm/gems/ruby-2.3.3/gems/database_cleaner-1.5.3/lib/database_cleaner/generic/base.rb:16:in `cleaning'
     # /home/victor/.rvm/gems/ruby-2.3.3/gems/database_cleaner-1.5.3/lib/database_cleaner/base.rb:98:in `cleaning'
     # /home/victor/.rvm/gems/ruby-2.3.3/gems/database_cleaner-1.5.3/lib/database_cleaner/configuration.rb:86:in `block (2 levels) in cleaning'
     # /home/victor/.rvm/gems/ruby-2.3.3/gems/database_cleaner-1.5.3/lib/database_cleaner/configuration.rb:87:in `cleaning'
     # ./spec/rails_helper.rb:39:in `block (2 levels) in <top (required)>'

Finished in 12.79 seconds (files took 4.73 seconds to load)
3 examples, 1 failure

Failed examples:

rspec ./spec/features/comments_spec.rb:49 # commenting as an account's owner rejecting a note`

Could you help me please?

**Comment by radar** [comment]
This issue might happen if you didn't check out the submodules:

```
git submodule update --init
```

**Comment by victor-soto** [comment]
Nope, I executed this command and issue persist, my comments_spec.rb looks like:

```require 'rails_helper'

describe 'commenting' do 
  let!(:account) { FactoryGirl.create(:account) }
  let!(:reviewer) { create_user! }
  let!(:book) { create_book! }
  let!(:chapter) { book.chapters.first }
  let!(:element) { chapter.elements.first }
  let!(:note) { element.notes.create(:user => reviewer, :text => "My favourite element.", :number => 1) }
  let!(:comment_text) { "This is a typical comment" }

  def assert_comment_form_blank!
    expect(find("#comment_text").text).to be_blank
  end

  def assert_comment_present!
    within("#comments") do
      expect(page).to have_content(comment_text)
    end
  end

  context "as an account's owner" do
    before do
      login_as(account.owner)
      set_subdomain(account.subdomain)
      visit book_note_url(book, note)
      fill_in "comment_text", :with => comment_text
    end

    it "a normal comment" do
      click_button "Leave Comment"
      within(".flash_notice") do
        expect(page).to have_content("Comment has been created.")
      end
      assert_comment_form_blank!
      assert_comment_present!
    end

    it "accepting a note" do
      click_button "Accept"
      within(".flash_notice") do
        expect(page).to have_content("Note state changed to Accepted")
      end
      expect(note.reload.state).to eq('accepted')
      assert_comment_form_blank!
      assert_comment_present!
    end

    it "rejecting a note" do
      click_button "Reject"
      within(".flash_notice") do
        expect(page).to have_content("Note state changed to Rejected")
      end
      expect(note.reload.state).to eq('rejected')
      assert_comment_form_blank!
      assert_comment_present!
    end
  end
end
```
