### ISSUE TITLE
Page 357 - Subscriptions can be canceled spec fails: spec/features/accounts/subscriptions_spec.rb

### ISSUE THREAD

**Issue by bryanbeshore** [radar/twist#29]
Pg. 357: spec/features/accounts/subscriptions_spec.rb

`1) Subscriptions can be cancelled
     Failure/Error: subscription = customer.subscriptions.create(plan: "starter")
     
     Stripe::InvalidRequestError:
       No such plan: starter
     # ./spec/features/accounts/subscriptions_spec.rb:20:in `block (2 levels) in <top (required)>'
     # ./spec/rails_helper.rb:40:in `block (3 levels) in <top (required)>'
     # ./spec/rails_helper.rb:39:in `block (2 levels) in <top (required)>'
     # ------------------
     # --- Caused by: ---
     # RestClient::BadRequest:
     #   400 Bad Request
     #   ./spec/features/accounts/subscriptions_spec.rb:20:in `block (2 levels) in <top (required)>'

Finished in 1.37 seconds (files took 5.41 seconds to load)
1 example, 1 failure

Failed examples:

rspec ./spec/features/accounts/subscriptions_spec.rb:30 # Subscriptions can be cancelled`

**Comment by bryanbeshore** [comment]
I am receiving this error when I attempt to create an account and process a payment for that account to be created. Payment seems to go through, but am redirected to this Invalid Request Error:

Stripe::InvalidRequestError in Accounts::PlansController#chosen

Received unknown parameter: source

`
customer = Stripe::Customer.retrieve(current_account.stripe_customer_id)
    plan = Plan.find(params[:account][:plan_id])
    subscription = customer.subscriptions.create(
      plan: plan.stripe_id,
      source: params[:token]
    )
`

**Comment by radar** [comment]
It is likely that Stripe's API has changed since I wrote that chapter. It will need to receive an update in the book. Thank you for letting me know of this issue.

**Comment by bryanbeshore** [comment]
Thanks for the reply, and I'll be doing some digging this weekend/next week to see if I can get this issue resolved or somewhat resolved. 

Also, to note, and this relates to the API change I think: on page 309 for the stripe_plan_fetcher_spec.rb you have:

`
describe StripePlanFetcher do
  let(:faux_plan) do
    double("plan",
              id: "starter",
              name: "Starter",
              amount: 995)
  end
`
name does not work. Needed to change to `nickname: "Starter",` to get it to work

For my original question, though, if you find any answer/workaround/thoughts that might be helpful to resolve I would be 100% all ears. My first time working with Stripe but there is a lot of documentation

**Comment by radar** [comment]
Looks like Stripe has switched from straight plans to having "products" with "pricing plans". Most of the chapter will need to be updated. No ETA on that, but at least it's on my radar now.

**Comment by bryanbeshore** [comment]
Thanks. It did seem like a few things were not 100% there, but for the most part things were moving along ok

Book is fantastic btw! Many thanks.
